config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  end

  resources :users

  # Login
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get "sign_in", to: "devise/sessions#new", as: :new_user_session
    delete "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  resources :proposals do
    member do
      post :comment
    end
  end

  resources :ideas do
    member do
      post :comment
    end
  end

  post "webhook", to: "proposals#webhook", as: :webhook

  constraints(path: /[^?]+/) do
    get "edit/:branch/*path", to: "edit#edit", format: false
    get "new/:branch", to: "edit#new", format: false
  end
  post "edit/message", to: "edit#message"
  post "edit/commit", to: "edit#commit"
  get "edit", to: "edit#index"

  root "proposals#index"
end

app/controllers/ideas_controller.rb
# frozen_string_literal: true

#
# Displays lists of submitted ideas, and individual idea pages.
#
class IdeasController < ApplicationController
  before_action :get_idea, except: [:index]
  before_action :authenticate_user!, only: [:comment]

  def index
    @ideas = Octokit.issues(Rails.application.config.groupthink[:github_repo],
      labels: "groupthink::idea")
  end

  def show
    @activity = []
    @author = User.find_or_create_by!(login: @idea.user.login)
    # Add original description
    @activity << ["comment", {
      body: @idea[:body].presence || "*The author didn't add any more detail*",
      user: @author,
      by_author: true,
      original_url: @idea[:html_url],
      time: @idea.created_at
    }]
    # Add comments
    comments = Octokit.issue_comments(Rails.application.config.groupthink[:github_repo],
      params[:id].to_i)
    @activity.concat(comments.map { |comment|
      ["comment", {
        body: comment.body,
        user: User.find_or_create_by(login: comment.user.login),
        by_author: (@author.login == comment.user.login),
        original_url: comment.html_url,
        time: comment.created_at
      }]
    })
    # Remove any empty elements
    @activity.compact!
    # Sort by time
    @activity.sort_by! { |a| a[1][:time] }
  end

  def comment
    user_github_connection.add_comment(Rails.application.config.groupthink[:github_repo],
      @idea["number"], params[:comment])
    redirect_to idea_path(@idea["number"])
  end

  private
    def get_idea
      @idea = Octokit.issue(Rails.application.config.groupthink[:github_repo], params[:id].to_i)
      raise ActiveRecord::RecordNotFound if @idea.nil?
    end
end

app/views/ideas/index.html.erb
<div class='pull-right'>
  <a href='https://github.com/<%= Rails.application.config.groupthink[:github_repo] %>/issues/new?labels=groupthink::idea' class='btn btn-primary' style='margin: 25px 0px'>
    <%= fa_icon 'plus' %>
    Suggest a new idea
  </a>
</div>

<h1>Ideas</h1>

<div class='alert alert-info' style='clear: both'>
  <p>
    This page lists outline ideas that have been suggested, but not turned into detailed
    proposals yet.
  </p>
  <p>
    If you're looking for something to contribute:
  </p>
  <ol>
    <li>pick something interesting from the list,</li>
    <li>click through to take a look at the details,</li>
    <li>then go and suggest a change!</li>
  </ol>
</div>

<table class='table table-striped'>
  <tr>
    <th>
      Idea
    </th>
    <th>
      When suggested
    </th>
  </tr>
  <% @ideas.each do |idea| %>
    <tr>
      <td>
        <%= link_to idea[:title], idea_path(idea[:number]) %>
      </td>
      <td>
        <%= time_ago_in_words(idea[:created_at]) %> ago
      </td>
    </tr>
  <% end %>
</table>

app/views/ideas/show.html.erb
<h1>
  <%= @idea.title %>
  <a href='<%= @idea.html_url %>'>
    <%= fa_icon 'github' %>
  </a>
</h1>

<hr/>

<div class='row'>

  <div class='col-md-9'>

    <% @activity.each do |x| %>
      <%= render partial: "shared/#{x[0]}", locals: x[1] %>
    <% end %>

    <div style="clear: both">
      <% if signed_in? %>
        <div class='panel panel-primary' id="vote">
          <div class="panel-heading">
            Comment:
          </div>
          <div class='panel-body'>
            <%= form_tag comment_idea_path(@idea['number']) do %>
              <div class="form-group">
                <%= text_area_tag :comment, "", {rows: 5, class: "form-control"} %>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            <% end %>
          </div>
        </div>
      <% else %>
        <%= link_to ("#{t(:sign_in)} to comment "+fa_icon("sign-in")).html_safe, new_user_session_path, class: "btn btn-primary" %>
      <% end %>
    </div>

  </div>

  <div class='col-md-3'>

    <div>
      <div class='alert alert-info'>
        This is just a suggestion for a proposal, not a completed proposal. It
        should be turned into a proper proposal by editing the original document.
        Debate and voting can then happen there.
      </div>

      <p>
        <a href='<%= ENV.fetch("PROJECT_URL")%>' class='btn btn-primary btn-block'>
          <%= fa_icon 'edit' %> Make a proposal on this idea!
        </a>
      </p>
    </div>

  </div>

</div>