config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  end

  resources :users

  # Login
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get "sign_in", to: "devise/sessions#new", as: :new_user_session
    delete "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  resources :proposals do
    member do
      post :comment
    end
  end

  resources :ideas do
    member do
      post :comment
    end
  end

  post "webhook", to: "proposals#webhook", as: :webhook

  constraints(path: /[^?]+/) do
    get "edit/:branch/*path", to: "edit#edit", format: false
    get "new/:branch", to: "edit#new", format: false
  end
  post "edit/message", to: "edit#message"
  post "edit/commit", to: "edit#commit"
  get "edit", to: "edit#index"

  root "proposals#index"
end

app/models/proposal.rb
# frozen_string_literal: true

#
# A proposed change to the repository.
# Underneath, this is a GitHub pull request.
#
class Proposal < ApplicationRecord
  include Votable
  include GithubPullRequest

  default_scope { order(number: :desc) }
  paginates_per 10

  has_many :interactions, dependent: :destroy
  has_many :participants, through: :interactions, source: :user
  belongs_to :proposer, class_name: "User"

  validates :number, presence: true, uniqueness: true
  validates :state, inclusion: { in: %w(waiting agreed passed blocked dead accepted rejected) }
  validates :title, presence: true
  validates :proposer, presence: true

  before_validation :load_from_github, on: :create
  after_create :queue_vote_count
  after_create :notify_voters

  scope :closed, -> { where(state: %w(accepted rejected)) }
  scope :open, -> { where(state: %w(waiting agreed passed blocked dead)) }

  def update_from_github!
    load_from_github
    count_votes! unless closed?
    save!
  end

  def load_from_github
    self.opened_at ||= github_pr.created_at
    self.title     ||= github_pr.title
    self.state     ||= "waiting"
    self.proposer  ||= User.find_or_create_by!(login: github_pr.user.login)
  end

  def age
    (Time.zone.today - opened_at.to_date).to_i
  end

  def too_old?
    age >= Settings.max_age
  end

  def too_new?
    age < Settings.min_age
  end

  def update_state!
    state = pr_closed? ? closed_state : open_state
    update!(state: state)
  end

  def close_if_dead!
    close_pr! if state == "dead"
  end

  def close!
    proposer.update_author_status_from_github && proposer.save!
    update_state!
  end

  def closed?
    %w(accepted rejected).include? state
  end

  def notify_voters
    # Notify users that there is a new proposal to vote on
    User.where.not(email: nil).where(notify_new: true).all.find_each do |user|
      ProposalsMailer.new_proposal(user, self).deliver_later if user.can_vote? && user != proposer
    end
  end

  def to_param
    number.to_s
  end

  private
    def closed_state
      return nil unless pr_closed?
      pr_merged? ? "accepted" : "rejected"
    end

    def open_state
      return nil if pr_closed?
      return "dead" if too_old?
      return "blocked" if blocked?
      if passed?
        return too_new? ? "agreed" : "passed"
      end
      "waiting"
    end
end

app/controllers/proposals_controller.rb
# frozen_string_literal: true

#
# Shows proposal pages and handles webhook updates from GitHub.
#
class ProposalsController < ApplicationController
  protect_from_forgery except: :webhook
  before_action :get_proposal, except: [:index, :webhook]
  before_action :authenticate_user!, only: [:comment]

  def index
    @open_proposals = Proposal.open
    @closed_proposals = Proposal.closed.page params[:page]
  end

  def show
    @is_author = current_user == @proposal.proposer
    # Can the current user vote?
    @can_vote = current_user.try(:can_vote?) && !@is_author
    # Get activity list
    presenter = ProposalPresenter.new(@proposal)
    @activity = presenter.activity_log
  end

  def webhook
    case request.env["HTTP_X_GITHUB_EVENT"]
    when "issue_comment"
      on_issue_comment(JSON.parse(params[:payload]))
      head 200
    when "pull_request"
      on_pull_request(JSON.parse(params[:payload]))
      head 200
    when "ping"
      head 200
    else
      head 400
    end
  end

  def comment
    comment = params[:comment]
    case params[:vote]
    when "yes"
      comment += "\n\nVote: ✅"
    when "no"
      comment += "\n\nVote: ❎"
    when "abstention"
      comment += "\n\nVote: 🤐"
    when "block"
      comment += "\n\nVote: 🚫"
    end
    user_github_connection.add_comment(Rails.application.config.groupthink[:github_repo],
      @proposal.number, comment)
    redirect_to @proposal
  end

  private
    def get_proposal
      @proposal = Proposal.find_by(number: params[:id])
      raise ActiveRecord::RecordNotFound if @proposal.nil?
    end

    def on_issue_comment(json)
      case json["action"]
      when "created"
        on_issue_comment_created(json)
      end
    end

    def on_pull_request(json)
      case json["action"]
      when "opened"
        on_pull_request_opened(json)
      when "closed"
        on_pull_request_closed(json)
      end
    end

    def on_issue_comment_created(json)
      issue = json["issue"]
      if issue["state"] == "open" && issue["pull_request"]
        UpdateProposalJob.perform_later issue["number"].to_i
      end
    end

    def on_pull_request_opened(json)
      # Delay creation by a few seconds in case the proposal is already being created elsewhere
      # This is necessary because we were getting race conditions in job creation
      CreateProposalJob.set(wait: 5.seconds).perform_later(json["number"].to_i)
    end

    def on_pull_request_closed(json)
      CloseProposalJob.perform_later(json["number"].to_i)
    end
end

app/helpers/proposals_helper.rb
# frozen_string_literal: true

#
# Helper methods for Proposal views
#
module ProposalsHelper
  def render_github_markdown(markdown)
    markdown = replace_emoji(markdown)
    markdown = GitHub::Markup.render("comment.markdown", markdown).html_safe
    markdown = link_usernames(markdown)
    markdown = link_proposals(markdown)
    auto_link(markdown)
  end

  EMOJI_REPLACEMENTS = [
    [":white_check_mark:", "✅"],
    [":negative_squared_cross_mark:", "❎"],
    [":no_entry_sign:", "🚫"],
    [":thumbsup:", "👍"],
    [":thumbsdown:", "👎"],
    [":+1:", "👍"],
    [":-1:", "👎"],
    [":hand:", "✋"],
    [":smiley:", "😃"],
  ]

  def replace_emoji(str)
    EMOJI_REPLACEMENTS.each do |replacement|
      str = str.gsub(replacement[0], replacement[1])
    end
    str
  end

  def link_usernames(str)
    str.scan(/(\s|^|>)@(\w+)/).each do |match|
      str = str.gsub "@#{match[1]}", "<a href='/users/#{match[1]}'>@#{match[1]}</a>"
    end
    str.html_safe
  end

  def link_proposals(str)
    str.scan(/(\s|^|>)#(\d+)/).each do |match|
      str = str.gsub "##{match[1]}", "<a href='/proposals/#{match[1]}'>##{match[1]}</a>"
    end
    str.html_safe
  end

  def ignore_diff_line?(line)
    ["@", "---", "+++"].any? do |prefix|
      line.starts_with?(prefix)
    end
  end

  def diff_line_type(line)
    # Ignore some lines completely
    return nil if ignore_diff_line?(line)
    # Detect type
    {
      "+": :added,
      "-": :removed,
      " ": :unchanged
    }[line[0].to_sym]
  end

  def parse_diff_line(line)
    line_type = diff_line_type(line)
    line_type ? [line_type, line[1..-1]] : nil
  end

  def chunk_diff(diff)
    # Parse all lines
    lines = [[:unchanged, ""]]
    lines += diff.split("\n").filter_map { |line| parse_diff_line(line) }
    # Detect groups where the line type changes
    grouped_lines = lines.slice_when { |before, after| before[0] != after[0] }
    # Merge grouped lines into a single chunk
    grouped_lines.map { |x| [x[0][0], x.map { |y| y[1] }.join("\n")] }
  end

  def render_diff(diff)
    return "" if diff.nil?
    chunk_diff(diff).map do |section|
      "<div class='diff #{section[0]}'>#{render_github_markdown(section[1]).strip}</div>"
    end.join
  end
end

app/views/proposals/_comment.html.erb
<% by_proposer = (user == proposal.proposer) %>
<% boxclass = 'well' %>
<% boxclass = 'alert alert-danger' if body.contains_block? %>
<% boxclass = 'alert alert-warning' if body.contains_no? %>
<% boxclass = 'alert alert-success' if body.contains_yes? %>
<div class='comment <%= boxclass %> <%= by_proposer ? 'pull-left' : 'pull-right' %>'  style='width: 75%'>
  <p class='<%= by_proposer ? 'pull-left' : 'pull-right' %>'>
    <%= render partial: 'shared/person', locals: { person: user } %>
  </p>
  <p>
    <%= link_to "@#{user.login}", user %> - <%= link_to time_ago_in_words(time)+" ago", original_url %></small>
  </p>
  <p>
    <%= render_github_markdown(body) %>
  </p>
</div>

app/views/proposals/index.html.erb
<h1>Open Proposals</h1>

<div class='alert alert-info' style='clear: both'>
  <p>
    This page lists suggested changes to the manifesto. Open proposals are ready
    for comments and must be voted on before they can be included in the manifesto.
    You can only vote on proposals if you have already successfully contributed a
    change to the manifesto.
  </p>
  <p>
    To create your own proposal:
  </p>
  <ol>
    <li>pick a subject you are interested in,</li>
    <li>find a suitable page in the manifesto,</li>
    <li>click on the "Suggest a change" button!</li>
  </ol>
</div>

<%= render partial: 'shared/proposal_list', locals: {proposals: @open_proposals} %>

<h1>Closed Proposals</h1>

<%= render partial: 'shared/proposal_list', locals: {proposals: @closed_proposals} %>

<div style="text-align: center">
  <%= paginate @closed_proposals %>
</div>

app/views/proposals/index.json.erb
{
  "count": <%= Proposal.count %>,
  "open": {
    "count": <%= @open_proposals.count %>,
    "waiting": <%= Proposal.where(state: "waiting").count %>,
    "agreed": <%= Proposal.where(state: "agreed").count %>,
    "passed": <%= Proposal.where(state: "passed").count %>,
    "blocked": <%= Proposal.where(state: "blocked").count %>,
    "dead": <%= Proposal.where(state: "dead").count %>
  },
  "closed": {
    "count": <%= @closed_proposals.count %>,
    "accepted": <%= Proposal.where(state: "accepted").count %>,
    "rejected": <%= Proposal.where(state: "rejected").count %>
  }
}

app/views/proposals/show.html.erb
<h1>
  <%= @proposal.title %>
  <a href='<%= @proposal.url %>'>
    <%= fa_icon 'github' %>
  </a>
</h1>

<div class='row' style='text-align: center'>
  <div class='col-md-3 user'>
    Proposer
    <br/>
    <%= render partial: 'shared/person', locals: { person: @proposal.proposer } %>
  </div>
  <div class='col-md-3'>
    State
    <br/>
    <h2>
      <span class='label label-<%= row_class(@proposal) %>'>
        <%= state_icon(@proposal.state) %>
        <%= @proposal.state.capitalize %>
      </span>
    </h2>
  </div>
  <div class='col-md-3'>
    Vote Score
    <br/>
    <% rowclass = @proposal.blocked? ? "danger" : "warning" %>
    <% rowclass = 'success' if @proposal.passed? %>
    <h2><span class='label label-<%= rowclass %>'><%= @proposal.score %></span></h2>
  </div>
  <div class='col-md-3'>
    Age
    <br/>
    <h2>
      <% rowclass = @proposal.too_old? || @proposal.too_new? ? "danger" : "success" %>
      <span class='label label-<%= rowclass %>'><%= @proposal.age %> days</span>
    </h2>
  </div>
</div>

<% if @proposer_needs_to_sign_cla %>
  <div class='row'>
    <%= render partial: 'shared/cla_warning', locals: { user: @proposal.proposer } %>
  </div>
<% end %>

<hr/>

<div class='row'>

  <div class='col-md-9'>

    <% @activity.each do |x| %>
      <%= render partial: "shared/#{x[0]}", locals: x[1] %>
    <% end %>

    <% if signed_in? %>
      <div style="clear: both">
        <div class='panel panel-primary' id="vote">
          <div class="panel-heading">
            Comment<% if @can_vote %> and vote<% end %>:
          </div>
          <div class='panel-body'>
            <%= form_tag comment_proposal_path(@proposal) do %>
              <div class="form-group">
                <%= text_area_tag :comment, "", {rows: 5, class: "form-control"} %>
              </div>
              <% if @can_vote %>
                <div class="form-group">
                  <label class="radio-inline">
                    <input type="radio" name="vote" id="vote-none" value="none" checked="true"> Not voting
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="vote" id="vote-yes" value="yes"> <%= vote_icon('yes') %> Yes
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="vote" id="vote-no" value="no"> <%= vote_icon('no') %> No
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="vote" id="vote-abstention" value="abstention"> <%= vote_icon('abstention') %> Abstain
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="vote" id="vote-block" value="block"> <%= vote_icon('block') %> Block
                  </label>
                </div>
              <% end %>
              <button type="submit" class="btn btn-primary">Submit</button>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

  </div>

  <div class='col-md-3'>

    <% if !signed_in? %>
      <div>
        <p>
          <%= link_to ("#{t(:sign_in)} to comment and vote "+fa_icon("sign-in")).html_safe,
                new_user_session_path, class: 'btn btn-primary btn-block'
          %>
        </p>
      </div>
    <% end %>

    <% if @can_vote %>
      <div class='hidden-sm hidden-xs'>
        <p>
          <a href='#vote' class='btn btn-primary btn-block'>
            <%= fa_icon 'check' %> Vote now!
          </a>
        </p>
      </div>
    <% end %>

    <div class='panel panel-default hidden-sm hidden-xs''>
      <div class="panel-heading">
        Activity
      </div>
      <div class='panel-body'>
        <% @proposal.participants.each do |user| %>
          <div class='alert alert-<%= user_row_class(user.vote(@proposal)) %>'>
            <%= render partial: 'shared/person', locals: { person: user, size: "small" } %>
            <%= vote_icon(user.vote(@proposal), size: "lg") %>
          </div>
        <% end %>
      </div>
    </div>

  </div>

</div>