config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  end

  resources :users

  # Login
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get "sign_in", to: "devise/sessions#new", as: :new_user_session
    delete "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  resources :proposals do
    member do
      post :comment
    end
  end

  resources :ideas do
    member do
      post :comment
    end
  end

  post "webhook", to: "proposals#webhook", as: :webhook

  constraints(path: /[^?]+/) do
    get "edit/:branch/*path", to: "edit#edit", format: false
    get "new/:branch", to: "edit#new", format: false
  end
  post "edit/message", to: "edit#message"
  post "edit/commit", to: "edit#commit"
  get "edit", to: "edit#index"

  root "proposals#index"
end

app/controllers/edit_controller.rb
# frozen_string_literal: true

#
# Allow users to propose new changes.
#
class EditController < ApplicationController
  before_action :get_parameters
  before_action :check_logged_in

  extend Memoist
  GITHUB_REPO_REGEX = /github.com[:\/]([^\/]*)\/([^.]*)/

  def new
    @content = ""
  end

  def edit
    @content = get_files(original_repo_path, @filename)[@filename]
    @lineendings = detect_line_endings(@content)
  end

  def message
    # Prepend title if we have been given one, for a new filename
    if @title.present?
      @content = "---\ntitle: #{@title}\n---\n#{@content}"
    end
    # Prepare a fork if we don't have permission to push
    unless user_github_connection.repository(original_repo_path).permissions.push
      user_github_connection.fork original_repo_path
    end
  end

  def commit
    # Fix line endings
    @content = convert_line_endings(@content, @lineendings)
    # Do we need to work in a fork?
    forked = !user_github_connection.repository(original_repo_path).permissions.push
    repo_path = forked ? user_repo_path : original_repo_path
    # Get the SHA of the edited branch - this is the head we want to add to
    base_sha = user_github_connection.tree(original_repo_path, @branch, recursive: true).sha
    # What shall we call our new branch?
    branch_name = Time.zone.now.to_s(:number)
    # Update fork if appropriate by making a new branch from the upstream base SHA
    # We do this even if not forking, as there's no harm in doing so
    create_branch(repo_path, branch_name, base_sha)
    # Commit the file on our new branch
    new_branch = commit_file(repo_path, @filename, @content, @summary, base_sha, branch_name)
    # open PR
    pull_from = forked ? "#{@current_user.login}:#{new_branch}" : branch_name
    @pr = open_pr(pull_from, @branch, @summary, @description)
    # Check for CLA
    @cla_url = "#{ENV.fetch("SITE_URL")}/cla.html"
    r = Faraday.get @cla_url
    @has_cla = (r.status == 200)
  end

  private
    def check_logged_in
      unless user_signed_in?
        redirect_to new_user_session_path
      end
    end

    def get_parameters
      @owner = params[:owner]
      @repo = params[:repo]
      @branch = params[:branch]
      @title = params[:title]
      @filename = params[:filename] || params[:path]
      @format = params[:format] || (@filename ? @filename.split(".").last : "md")
      if @title.present? && @filename.nil?
        @filename = @title.parameterize + ".#{@format}"
      end
      @content = params[:content]
      @summary = params[:summary]
      @description = params[:description]
      @lineendings = params[:lineendings] || :crlf
    end

    def original_repo_path
      ENV.fetch("GITHUB_REPO")
    end

    def user_repo_path
      repo_name = ENV.fetch("GITHUB_REPO").split("/").last
      "#{current_user.login}/#{repo_name}"
    end

    def branch
      params[:branch]
    end


    def latest_commit(repo, branch_name)
      branch_data = user_github_connection.branch repo, branch_name
      branch_data["commit"]["sha"]
    end
    memoize :latest_commit

    def tree(repo, branch)
      user_github_connection.tree(repo, branch, recursive: true)
    end
    memoize :tree

    def blob_shas(repo, branch, path)
      tree = tree(repo, branch).tree
      Hash[tree.filter_map { |x|
        [x.path, x.sha] if x[:path] =~ /^#{path}$/ && x[:type] == "blob"
      } ]
    end
    memoize :blob_shas

    def blob_content(repo, sha)
      blob = user_github_connection.blob repo, sha
      if blob["encoding"] == "base64"
        Base64.decode64(blob["content"])
      else
        blob["content"]
      end
    end
    memoize :blob_content


    def create_blob(repo, content)
      user_github_connection.create_blob repo, content, "utf-8"
    end

    def add_blob_to_tree(repo, blob_sha, filename, base_sha)
      new_tree = user_github_connection.create_tree repo, [{
        path: filename,
        mode: "100644",
        type: "blob",
        sha: blob_sha
      }], base_tree: base_sha
      new_tree.sha
    end

    def get_files(repo, name)
      blobs = blob_shas(repo, @branch, name)
      Hash[blobs.map { |x| [x[0], blob_content(repo, x[1])] }]
    end

    def commit_sha(repo, sha, message, parent_sha)
      commit = user_github_connection.create_commit repo, message, sha, parent_sha
      commit.sha
    end

    def create_branch(repo, name, sha)
      branch = user_github_connection.create_reference repo, "heads/#{name}", sha
      branch.ref
    end

    def update_branch(repo, name, sha)
      branch = user_github_connection.update_reference repo, "heads/#{name}", sha
      branch.ref
    end

    def open_pr(head, base, title, description)
      pr = user_github_connection.create_pull_request(
        original_repo_path, base, head, title, description,
        labels: ["groupthink::proposal"]
      )
      Proposal.find_or_create_by!(
        number: pr.number,
        opened_at: Time.zone.now,
        title: title,
        proposer: @current_user
      )
    end

    def commit_file(repo, name, content, message, base_sha, branch_name)
      blob_sha = create_blob(repo, content)
      tree_sha = add_blob_to_tree(repo, blob_sha, name, base_sha)
      commit_sha = commit_sha(repo, tree_sha, message, base_sha)
      update_branch(repo, branch_name, commit_sha)
    end

    def detect_line_endings(str)
      case str
      when /\r\n/
        :crlf
      when /\r/
        :cr
      when /\n/
        :lf
      else
        nil
      end
    end

    def convert_line_endings(str, lineendings)
      case lineendings.to_sym
      when :cr
        str.gsub("\r\n", "\r")
      when :lf
        str.gsub("\r\n", "\n")
      else
        str
      end
    end
end

app/views/edit/_csv_editor.html.erb
<div id='example' class="handsontable">
</div>
<script>
  var data = Papa.parse("<%= escape_javascript(@content).html_safe %>").data;
  var container = document.getElementById('example');

  hot = new Handsontable(container, {
    data: data,
    minSpareRows: 1,
    contextMenu: true,
    afterChange: function (change, source) {
      if (source == "edit") {
        $('#content').val(Papa.unparse(data));
      }
    }
  });
  
</script>

<%= hidden_field_tag 'content', @content %>

app/views/edit/_edit_form.html.erb
<div class="form-group">
  <%= case @format
  when "csv"
    render 'csv_editor' 
  when "md"
    render 'markdown_editor' 
  else
    render 'text_editor'
  end %>
</div>

<%= hidden_field_tag "owner", @owner %>
<%= hidden_field_tag "repo", @repo %>
<%= hidden_field_tag "branch", @branch %>
<%= hidden_field_tag "lineendings", @lineendings %>
<%= hidden_field_tag "format", @format %>

<div class="form-group">
  <%= submit_tag t(:submit_changes), class: 'btn btn-primary'%>
</div>

app/views/edit/_markdown_editor.html.erb
<link rel="stylesheet" href="https://unpkg.com/easymde@2.9.0/dist/easymde.min.css" integrity="sha384-FAuhUTeRrv9xA8b+724/Hfc69EqCqbySHAtoLXt2pVIevuLQ5YBiegzQULs6WKrh" crossorigin="anonymous">
<script src="https://unpkg.com/easymde@2.9.0/dist/easymde.min.js" integrity="sha384-N2niw6YEQdfj573L2ygSuhCNfIonz8O1jnPRZa2kn+KpMSHfjnpM0Fr/t4yG9PFS" crossorigin="anonymous"></script>

<div class='row'>
  <div class='col-md-8'>
    <%= text_area_tag 'content', @content, style: 'width: 100%; min-height: 700px; font-family: monospace' %>
  </div>
  <div class='col-md-4'>
    <small>
    <p>
      This file is written using <a href="https://help.github.com/articles/basic-writing-and-formatting-syntax/">Markdown</a>, a simple text formatting method.
    </p>
    <h4>Headings</h4>
    <p>
      Headings use <code>#</code> at the start of the line. Smaller headings use more <code>#</code> symbols.
    </p>
    <pre># Top-level heading
## Second-level heading
### Third-level heading</pre>
    <h4>Links</h4>
    <p>
      Create links by putting square brackets around the text to link, and then the URL in round brackets afterwards:
    </p>
    <pre>Visit [Wikipedia](https://wikipedia.org).</pre>
    <h4>Lists</h4>
    <p>
      Create bulleted lists by using a <code>* </code> with a space after at the start of each line.
      Use <code>1. </code> with a space after to create numbered lists. You don't need to change the number each time.
    </p>
    <pre>* Bulleted
* List

1. Numbered
1. List</pre>
    <h4>Styling</h4>
    <p>
      To create italic text, surround it with a single <code>*</code>:
    </p>
    <pre>This is in *italics*</pre>
    <p>
      For bold text, surround it with two stars:
    </p>
    <pre>This is in **bold**</pre>
    <h4>Footnotes</h4>
    <p>
      To create footnotes, add a unique id in your text like so:
    </p>
    <pre>[^my-unique-id]</pre>
    <p>
      and then before the next paragraph, add the footnote:
    </p>
    <pre>[^my-unique-id]: This is the footnote text.</pre>
  </small>
  </div>
</div>

<script>
var easyMDE = new EasyMDE({
  hideIcons: ["heading", "image", "fullscreen", "side-by-side"],
  showIcons: ["heading-2", "heading-3"],
  status: false,
  autofocus: true
});
</script>

app/views/edit/_text_editor.html.erb
<%= text_area_tag 'content', @content, style: 'width: 100%; height: 500px; font-family: monospace' %>

app/views/edit/commit.html.erb
<div class="form-group alert alert-success">
  <%= fa_icon 'check-circle' %>
  <%= t 'help.success_title' %>
</div>

<div class="form-group">
  <p>
    <%= t 'help.success' %>
  </p>
</div>

<div class="form-group">
  <%= link_to "#{fa_icon('globe')} #{t(:return)}".html_safe, @return_to, class: 'btn btn-primary' if @return_to %>
  <%= link_to "#{fa_icon('code-fork')} #{t(:view)}".html_safe, proposal_path(@pr), class: 'btn btn-default' %>
  <%= link_to "#{fa_icon('list')} #{t(:view_all)}".html_safe, proposals_path, class: 'btn btn-default' %>
</div>

<% if @proposer_needs_to_sign_cla %>
  <%= render partial: 'shared/cla_warning', locals: { user: current_user } %>
<% end %>

app/views/edit/edit.html.erb
<%= form_tag action: 'message' do %>

<div class='pull-right'>
  <a class='btn btn-success' href='/new/<%= @branch%>'>
    <%= fa_icon 'plus' %>
    Create new file instead
  </a>
</div>

<h1>Suggest a change to <em><%= @filename %></em></h1>

<div class="form-group alert alert-success">
  <%= fa_icon 'question-circle' %>
  <%= t 'help.edit' %>
</div>

<%= hidden_field_tag "filename", @filename %>

<%= render 'edit_form' %>

<% end %>

app/views/edit/message.html.erb
<%= form_tag action: 'commit' do %>

<h1>Describe your suggestion</h1>

<div class="form-group alert alert-success">
  <%= fa_icon 'question-circle' %>
  <%= t 'help.summary' %>
</div>

<div class="form-group">
  <%= text_field_tag 'summary', '', style: 'width: 100%', maxlength: "100", placeholder: "write a short summary of your change here", required: true %>
</div>

<div class="form-group alert alert-info">
  <%= fa_icon 'question-circle' %>
  <%= t 'help.description' %>
</div>

<div class="form-group">
  <%= text_area_tag 'description', '', style: 'width: 100%; height: 100px', placeholder: "write a more detailed explanation here if you want to" %>
</div>

<%= hidden_field_tag "filename", @filename %>
<%= hidden_field_tag "owner", @owner %>
<%= hidden_field_tag "repo", @repo %>
<%= hidden_field_tag "branch", @branch %>
<%= hidden_field_tag "content", @content %>
<%= hidden_field_tag "lineendings", @lineendings %>

<div class="form-group">
  <%= submit_tag t(:submit_changes), class: 'btn btn-primary'%>
</div>

<% end %>

app/views/edit/new.html.erb
<%= form_tag action: 'message' do %>

<h1>Create a new file</h1>

<div class="form-group alert alert-success">
  <%= fa_icon 'question-circle' %>
  <%= t 'help.new' %>
</div>

<div class="form-group">
  <%= text_field_tag 'title', '', style: 'width: 100%', maxlength: "100", placeholder: "Enter the title for your new file", required: true %>
</div>

<%= render 'edit_form' %>

<% end %>