config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  end

  resources :users

  # Login
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get "sign_in", to: "devise/sessions#new", as: :new_user_session
    delete "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  resources :proposals do
    member do
      post :comment
    end
  end

  resources :ideas do
    member do
      post :comment
    end
  end

  post "webhook", to: "proposals#webhook", as: :webhook

  constraints(path: /[^?]+/) do
    get "edit/:branch/*path", to: "edit#edit", format: false
    get "new/:branch", to: "edit#new", format: false
  end
  post "edit/message", to: "edit#message"
  post "edit/commit", to: "edit#commit"
  get "edit", to: "edit#index"

  root "proposals#index"
end

app/views/layouts/application.html.erb
<html>
  <head>
    <title><%= ENV.fetch("PROJECT_NAME") %></title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="<%= bootstrap_url %>">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag ENV.fetch("FAVICON_URL"), type: 'image/png' if ENV.fetch("FAVICON_URL", nil) %>
    <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
    <style>
       body {
         padding-top: 50px;
       }
     </style>
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= ENV.fetch("PROJECT_URL") %>">
              <%= image_tag ENV.fetch("PROJECT_LOGO"), alt: "logo", height: "20", style: "vertical-align: text-bottom; display: inline-block" if ENV.fetch("PROJECT_LOGO", nil)%>&nbsp;<%= ENV.fetch("PROJECT_NAME") %>
            </a>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "Proposals", proposals_path %></li>
              <li><%= link_to "Ideas", ideas_path %></li>
              <li><%= link_to "People", users_path %></li>
              <% if can? :access, :rails_admin %><li><%= link_to "Admin", rails_admin_path %></li><% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if signed_in? %>
                <li><%= link_to fa_icon("sign-out lg"), destroy_user_session_path, method: "delete", class: 'sign-out' %></li>
                <li><%= link_to fa_icon("cog lg"), edit_user_path(current_user) %></li>
                <li class='toolbar-avatar'>
                  <%= render partial: "shared/person", locals: {person: current_user, size: "toolbar"} %>
                </li>
              <% else %>
                <li><%= link_to (t(:sign_in)+" "+fa_icon("sign-in")).html_safe, new_user_session_path %></li>
              <% end %>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>

    <div class='container'>

      <% if notice %>
        <div class="alert alert-info"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-warning"><%= alert %></div>
      <% end %>

      <%= yield %>

      <footer class='well'>
        Code available on <a href='https://github.com/openpolitics/groupthink'>GitHub</a>. Error tracking generously provided by <a href='http://bugsnag.com'>Bugsnag</a>.
      </footer>

    </div>

    <script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

  </body>
</html>